source 'https://rubygems.org'

group :development, :test do
  gem 'jekyll', '~> 3.3.1'
  gem 'jekyll-redirect-from', '~> 0.12.0'
  gem 'jekyll-sitemap', '~> 0.12.0'
  gem 'scss_lint', '~> 0.51.0'
  gem 'bootstrap', '~> 4.2.1'
  gem 'jquery-rails'

end

gem 'popper_js', '~> 1.11.1'
gem 'bootstrap', '4.0.0.alpha6'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.3.3'
end